Repository OpenCodeEra/Open-Code-Era-2.0, pull requests merged in 2023-10, with the labels that each got.

#1 Add essential files
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  index.html
  pages/about.html
  pages/collaborate.html
  pages/contact.html
  pages/event.html
  pages/projects.html
  pages/socials.html
  public/images/code-solid.svg
  styles/globals.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#4 final change before opening for HacktoberFest
  pages/projects.html
  pages/socials.html
  styles/about.css
  styles/globals.css
  styles/projects.css
Labels: hacktoberfest, hacktoberfest-accepted

#17 Correct redirect of home link page in other pages.
  pages/about.html
  pages/collaborate.html
  pages/contact.html
  pages/event.html
  pages/projects.html
  pages/socials.html
Labels: hacktoberfest, hacktoberfest-accepted, fixed

#22 Updated CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#23 Updated README.md
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#25 Added Code-of-Conduct.md
  CODE_OF_CONDUCT.md
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted
